### ISSUE TITLE
No issue :v 

### ISSUE THREAD

**Issue by MinhPT-99** [ngapt6868/ngapt6868.github.io#1]
Bài làm tốt, chuẩn form, bố cục đẹp, ảnh đẹp, cách chia div hợp lí. A muốn hỏi 1 câu như sau: E có thấy những thuộc tính như width, height hay text-align phải viết đi viết lại giống nhau và rất nhiều lần không? Giải quyết như thế nào được nhỉ? :C giúp a nhé

**Comment by ngapt6868** [comment]
Em thưa anh, cách giải quyết của em là thêm css ạ

Vào Th 2, 7 thg 10, 2019 vào lúc 21:19 Phan Tuấn Minh <
notifications@github.com> đã viết:

**Comment by minhpt99** [comment]
Wow, chuẩn luôn. sao đến học, lúc a hỏi ko dơ tay??
