### ISSUE TITLE
Issue BTVN Buổi 2

### ISSUE THREAD

**Issue by MinhPT-99** [ngapt6868/ngapt6868.github.io#2]
Em nộp sai link rồi kìa, Phải là ngapt6868.github.io/BTVN_Buoi2/buoi_2.html chứ. Buổi 2 chia chuẩn thế. Tuy nhiên vẫn hơi bị hack đấy nhé, khoảng trống giữa các div phải là margin chứ k phải border đâu nhé. Sai rồi, toang hết rồi. @@

**Comment by ngapt6868** [comment]
thế bài em a chưa xem được ạ


Vào Th 3, 15 thg 10, 2019 vào lúc 23:44 Phan Tuấn Minh <
notifications@github.com> đã viết:

**Comment by minhpt99** [comment]
A xem được rồi mới nhận xét đc như kia chứ.
